services:
  app:
    image: eclipse-temurin:21
    ports:
      - 8081:8080
    volumes:
      - ./workspace:/workspace
      - jenk:/workspace/img
    working_dir: /workspace
    entrypoint: ["java", "-jar", "jenkins-0.0.1-SNAPSHOT.jar"]
    tty: true
    networks:
      - jenkins_net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenk:
    driver: local
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24
          gateway: 192.168.201.1